spring.application.name=Hospital-Appointment-And-Management-System
spring.datasource.url=jdbc:mysql://localhost:3306/hams_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.security.user.name=smruti
#spring.security.user.password=s@123

server.servlet.session.persistent=false
logging.level.org.hibernate.SQL=DEBUG

hospital.base_url=/api